// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tag.proto

package pb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	context "golang.org/x/net/context"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tag struct {
	TagId                *wrappers.StringValue `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Key                  *wrappers.StringValue `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *wrappers.StringValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Creator              *wrappers.StringValue `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp  `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{0}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTagId() *wrappers.StringValue {
	if m != nil {
		return m.TagId
	}
	return nil
}

func (m *Tag) GetKey() *wrappers.StringValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Tag) GetValue() *wrappers.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Tag) GetCreator() *wrappers.StringValue {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *Tag) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Tag) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type CreateTagRequest struct {
	Key                  *wrappers.StringValue `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                *wrappers.StringValue `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Creator              *wrappers.StringValue `protobuf:"bytes,3,opt,name=creator,proto3" json:"creator,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp  `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateTagRequest) Reset()         { *m = CreateTagRequest{} }
func (m *CreateTagRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTagRequest) ProtoMessage()    {}
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{1}
}

func (m *CreateTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTagRequest.Unmarshal(m, b)
}
func (m *CreateTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTagRequest.Marshal(b, m, deterministic)
}
func (m *CreateTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTagRequest.Merge(m, src)
}
func (m *CreateTagRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTagRequest.Size(m)
}
func (m *CreateTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTagRequest proto.InternalMessageInfo

func (m *CreateTagRequest) GetKey() *wrappers.StringValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *CreateTagRequest) GetValue() *wrappers.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *CreateTagRequest) GetCreator() *wrappers.StringValue {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *CreateTagRequest) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *CreateTagRequest) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type CreateTagResponse struct {
	TagId                *wrappers.StringValue `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CreateTagResponse) Reset()         { *m = CreateTagResponse{} }
func (m *CreateTagResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTagResponse) ProtoMessage()    {}
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{2}
}

func (m *CreateTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTagResponse.Unmarshal(m, b)
}
func (m *CreateTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTagResponse.Marshal(b, m, deterministic)
}
func (m *CreateTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTagResponse.Merge(m, src)
}
func (m *CreateTagResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTagResponse.Size(m)
}
func (m *CreateTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTagResponse proto.InternalMessageInfo

func (m *CreateTagResponse) GetTagId() *wrappers.StringValue {
	if m != nil {
		return m.TagId
	}
	return nil
}

type DescribeTagsRequest struct {
	TagId                []string             `protobuf:"bytes,1,rep,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Key                  []string             `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	Value                []string             `protobuf:"bytes,3,rep,name=value,proto3" json:"value,omitempty"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,5,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DescribeTagsRequest) Reset()         { *m = DescribeTagsRequest{} }
func (m *DescribeTagsRequest) String() string { return proto.CompactTextString(m) }
func (*DescribeTagsRequest) ProtoMessage()    {}
func (*DescribeTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{3}
}

func (m *DescribeTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTagsRequest.Unmarshal(m, b)
}
func (m *DescribeTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTagsRequest.Marshal(b, m, deterministic)
}
func (m *DescribeTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTagsRequest.Merge(m, src)
}
func (m *DescribeTagsRequest) XXX_Size() int {
	return xxx_messageInfo_DescribeTagsRequest.Size(m)
}
func (m *DescribeTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTagsRequest proto.InternalMessageInfo

func (m *DescribeTagsRequest) GetTagId() []string {
	if m != nil {
		return m.TagId
	}
	return nil
}

func (m *DescribeTagsRequest) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DescribeTagsRequest) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *DescribeTagsRequest) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *DescribeTagsRequest) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type DescribeTagsResponse struct {
	TotalCount           uint32   `protobuf:"varint,1,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Tags                 []*Tag   `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DescribeTagsResponse) Reset()         { *m = DescribeTagsResponse{} }
func (m *DescribeTagsResponse) String() string { return proto.CompactTextString(m) }
func (*DescribeTagsResponse) ProtoMessage()    {}
func (*DescribeTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{4}
}

func (m *DescribeTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DescribeTagsResponse.Unmarshal(m, b)
}
func (m *DescribeTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DescribeTagsResponse.Marshal(b, m, deterministic)
}
func (m *DescribeTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DescribeTagsResponse.Merge(m, src)
}
func (m *DescribeTagsResponse) XXX_Size() int {
	return xxx_messageInfo_DescribeTagsResponse.Size(m)
}
func (m *DescribeTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DescribeTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DescribeTagsResponse proto.InternalMessageInfo

func (m *DescribeTagsResponse) GetTotalCount() uint32 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

func (m *DescribeTagsResponse) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ModifyTagRequest struct {
	TagId                *wrappers.StringValue `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	Key                  *wrappers.StringValue `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value                *wrappers.StringValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyTagRequest) Reset()         { *m = ModifyTagRequest{} }
func (m *ModifyTagRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyTagRequest) ProtoMessage()    {}
func (*ModifyTagRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{5}
}

func (m *ModifyTagRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyTagRequest.Unmarshal(m, b)
}
func (m *ModifyTagRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyTagRequest.Marshal(b, m, deterministic)
}
func (m *ModifyTagRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyTagRequest.Merge(m, src)
}
func (m *ModifyTagRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyTagRequest.Size(m)
}
func (m *ModifyTagRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyTagRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyTagRequest proto.InternalMessageInfo

func (m *ModifyTagRequest) GetTagId() *wrappers.StringValue {
	if m != nil {
		return m.TagId
	}
	return nil
}

func (m *ModifyTagRequest) GetKey() *wrappers.StringValue {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ModifyTagRequest) GetValue() *wrappers.StringValue {
	if m != nil {
		return m.Value
	}
	return nil
}

type ModifyTagResponse struct {
	TagId                *wrappers.StringValue `protobuf:"bytes,1,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ModifyTagResponse) Reset()         { *m = ModifyTagResponse{} }
func (m *ModifyTagResponse) String() string { return proto.CompactTextString(m) }
func (*ModifyTagResponse) ProtoMessage()    {}
func (*ModifyTagResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{6}
}

func (m *ModifyTagResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyTagResponse.Unmarshal(m, b)
}
func (m *ModifyTagResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyTagResponse.Marshal(b, m, deterministic)
}
func (m *ModifyTagResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyTagResponse.Merge(m, src)
}
func (m *ModifyTagResponse) XXX_Size() int {
	return xxx_messageInfo_ModifyTagResponse.Size(m)
}
func (m *ModifyTagResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyTagResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyTagResponse proto.InternalMessageInfo

func (m *ModifyTagResponse) GetTagId() *wrappers.StringValue {
	if m != nil {
		return m.TagId
	}
	return nil
}

type DeleteTagsRequest struct {
	TagId                []string `protobuf:"bytes,1,rep,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagsRequest) Reset()         { *m = DeleteTagsRequest{} }
func (m *DeleteTagsRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteTagsRequest) ProtoMessage()    {}
func (*DeleteTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{7}
}

func (m *DeleteTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagsRequest.Unmarshal(m, b)
}
func (m *DeleteTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagsRequest.Marshal(b, m, deterministic)
}
func (m *DeleteTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagsRequest.Merge(m, src)
}
func (m *DeleteTagsRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteTagsRequest.Size(m)
}
func (m *DeleteTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagsRequest proto.InternalMessageInfo

func (m *DeleteTagsRequest) GetTagId() []string {
	if m != nil {
		return m.TagId
	}
	return nil
}

type DeleteTagsResponse struct {
	TagId                []string `protobuf:"bytes,1,rep,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTagsResponse) Reset()         { *m = DeleteTagsResponse{} }
func (m *DeleteTagsResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteTagsResponse) ProtoMessage()    {}
func (*DeleteTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{8}
}

func (m *DeleteTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTagsResponse.Unmarshal(m, b)
}
func (m *DeleteTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTagsResponse.Marshal(b, m, deterministic)
}
func (m *DeleteTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTagsResponse.Merge(m, src)
}
func (m *DeleteTagsResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteTagsResponse.Size(m)
}
func (m *DeleteTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTagsResponse proto.InternalMessageInfo

func (m *DeleteTagsResponse) GetTagId() []string {
	if m != nil {
		return m.TagId
	}
	return nil
}

type ResourceTag struct {
	ResourceTagId        *wrappers.StringValue `protobuf:"bytes,1,opt,name=resource_tag_id,json=resourceTagId,proto3" json:"resource_tag_id,omitempty"`
	ResourceId           *wrappers.StringValue `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	TagId                *wrappers.StringValue `protobuf:"bytes,3,opt,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	CreateTime           *timestamp.Timestamp  `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResourceTag) Reset()         { *m = ResourceTag{} }
func (m *ResourceTag) String() string { return proto.CompactTextString(m) }
func (*ResourceTag) ProtoMessage()    {}
func (*ResourceTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{9}
}

func (m *ResourceTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResourceTag.Unmarshal(m, b)
}
func (m *ResourceTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResourceTag.Marshal(b, m, deterministic)
}
func (m *ResourceTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResourceTag.Merge(m, src)
}
func (m *ResourceTag) XXX_Size() int {
	return xxx_messageInfo_ResourceTag.Size(m)
}
func (m *ResourceTag) XXX_DiscardUnknown() {
	xxx_messageInfo_ResourceTag.DiscardUnknown(m)
}

var xxx_messageInfo_ResourceTag proto.InternalMessageInfo

func (m *ResourceTag) GetResourceTagId() *wrappers.StringValue {
	if m != nil {
		return m.ResourceTagId
	}
	return nil
}

func (m *ResourceTag) GetResourceId() *wrappers.StringValue {
	if m != nil {
		return m.ResourceId
	}
	return nil
}

func (m *ResourceTag) GetTagId() *wrappers.StringValue {
	if m != nil {
		return m.TagId
	}
	return nil
}

func (m *ResourceTag) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

type AttachTagsRequest struct {
	TagId                []string `protobuf:"bytes,1,rep,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ResourceId           []string `protobuf:"bytes,2,rep,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachTagsRequest) Reset()         { *m = AttachTagsRequest{} }
func (m *AttachTagsRequest) String() string { return proto.CompactTextString(m) }
func (*AttachTagsRequest) ProtoMessage()    {}
func (*AttachTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{10}
}

func (m *AttachTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachTagsRequest.Unmarshal(m, b)
}
func (m *AttachTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachTagsRequest.Marshal(b, m, deterministic)
}
func (m *AttachTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachTagsRequest.Merge(m, src)
}
func (m *AttachTagsRequest) XXX_Size() int {
	return xxx_messageInfo_AttachTagsRequest.Size(m)
}
func (m *AttachTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AttachTagsRequest proto.InternalMessageInfo

func (m *AttachTagsRequest) GetTagId() []string {
	if m != nil {
		return m.TagId
	}
	return nil
}

func (m *AttachTagsRequest) GetResourceId() []string {
	if m != nil {
		return m.ResourceId
	}
	return nil
}

type AttachTagsResponse struct {
	TagId                []string `protobuf:"bytes,1,rep,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ResourceId           []string `protobuf:"bytes,2,rep,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AttachTagsResponse) Reset()         { *m = AttachTagsResponse{} }
func (m *AttachTagsResponse) String() string { return proto.CompactTextString(m) }
func (*AttachTagsResponse) ProtoMessage()    {}
func (*AttachTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{11}
}

func (m *AttachTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AttachTagsResponse.Unmarshal(m, b)
}
func (m *AttachTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AttachTagsResponse.Marshal(b, m, deterministic)
}
func (m *AttachTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AttachTagsResponse.Merge(m, src)
}
func (m *AttachTagsResponse) XXX_Size() int {
	return xxx_messageInfo_AttachTagsResponse.Size(m)
}
func (m *AttachTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AttachTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AttachTagsResponse proto.InternalMessageInfo

func (m *AttachTagsResponse) GetTagId() []string {
	if m != nil {
		return m.TagId
	}
	return nil
}

func (m *AttachTagsResponse) GetResourceId() []string {
	if m != nil {
		return m.ResourceId
	}
	return nil
}

type DetachTagsRequest struct {
	TagId                []string `protobuf:"bytes,1,rep,name=tag_id,json=tagId,proto3" json:"tag_id,omitempty"`
	ResourceId           []string `protobuf:"bytes,2,rep,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachTagsRequest) Reset()         { *m = DetachTagsRequest{} }
func (m *DetachTagsRequest) String() string { return proto.CompactTextString(m) }
func (*DetachTagsRequest) ProtoMessage()    {}
func (*DetachTagsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{12}
}

func (m *DetachTagsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachTagsRequest.Unmarshal(m, b)
}
func (m *DetachTagsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachTagsRequest.Marshal(b, m, deterministic)
}
func (m *DetachTagsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachTagsRequest.Merge(m, src)
}
func (m *DetachTagsRequest) XXX_Size() int {
	return xxx_messageInfo_DetachTagsRequest.Size(m)
}
func (m *DetachTagsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachTagsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetachTagsRequest proto.InternalMessageInfo

func (m *DetachTagsRequest) GetTagId() []string {
	if m != nil {
		return m.TagId
	}
	return nil
}

func (m *DetachTagsRequest) GetResourceId() []string {
	if m != nil {
		return m.ResourceId
	}
	return nil
}

type DetachTagsResponse struct {
	TagIds               []string `protobuf:"bytes,1,rep,name=tag_ids,json=tagIds,proto3" json:"tag_ids,omitempty"`
	ResourceIds          []string `protobuf:"bytes,2,rep,name=resource_ids,json=resourceIds,proto3" json:"resource_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetachTagsResponse) Reset()         { *m = DetachTagsResponse{} }
func (m *DetachTagsResponse) String() string { return proto.CompactTextString(m) }
func (*DetachTagsResponse) ProtoMessage()    {}
func (*DetachTagsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27f545bcde37ecb5, []int{13}
}

func (m *DetachTagsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetachTagsResponse.Unmarshal(m, b)
}
func (m *DetachTagsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetachTagsResponse.Marshal(b, m, deterministic)
}
func (m *DetachTagsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetachTagsResponse.Merge(m, src)
}
func (m *DetachTagsResponse) XXX_Size() int {
	return xxx_messageInfo_DetachTagsResponse.Size(m)
}
func (m *DetachTagsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetachTagsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetachTagsResponse proto.InternalMessageInfo

func (m *DetachTagsResponse) GetTagIds() []string {
	if m != nil {
		return m.TagIds
	}
	return nil
}

func (m *DetachTagsResponse) GetResourceIds() []string {
	if m != nil {
		return m.ResourceIds
	}
	return nil
}

func init() {
	proto.RegisterType((*Tag)(nil), "pb.Tag")
	proto.RegisterType((*CreateTagRequest)(nil), "pb.CreateTagRequest")
	proto.RegisterType((*CreateTagResponse)(nil), "pb.CreateTagResponse")
	proto.RegisterType((*DescribeTagsRequest)(nil), "pb.DescribeTagsRequest")
	proto.RegisterType((*DescribeTagsResponse)(nil), "pb.DescribeTagsResponse")
	proto.RegisterType((*ModifyTagRequest)(nil), "pb.ModifyTagRequest")
	proto.RegisterType((*ModifyTagResponse)(nil), "pb.ModifyTagResponse")
	proto.RegisterType((*DeleteTagsRequest)(nil), "pb.DeleteTagsRequest")
	proto.RegisterType((*DeleteTagsResponse)(nil), "pb.DeleteTagsResponse")
	proto.RegisterType((*ResourceTag)(nil), "pb.ResourceTag")
	proto.RegisterType((*AttachTagsRequest)(nil), "pb.AttachTagsRequest")
	proto.RegisterType((*AttachTagsResponse)(nil), "pb.AttachTagsResponse")
	proto.RegisterType((*DetachTagsRequest)(nil), "pb.DetachTagsRequest")
	proto.RegisterType((*DetachTagsResponse)(nil), "pb.DetachTagsResponse")
}

func init() { proto.RegisterFile("tag.proto", fileDescriptor_27f545bcde37ecb5) }

var fileDescriptor_27f545bcde37ecb5 = []byte{
	// 735 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0x55, 0xec, 0x24, 0xfd, 0x72, 0xdd, 0xf4, 0x6b, 0xa7, 0x2d, 0x8d, 0x42, 0x45, 0x8b, 0xc5,
	0xa2, 0x14, 0x6a, 0x8b, 0x54, 0x62, 0x01, 0x62, 0x11, 0xb5, 0x0b, 0xaa, 0x82, 0x84, 0x42, 0xc5,
	0x36, 0x1a, 0xc7, 0xd3, 0xc1, 0x22, 0xb5, 0x8d, 0x67, 0xd2, 0xaa, 0x5b, 0xc4, 0x13, 0x94, 0x97,
	0x40, 0xe2, 0x5d, 0x10, 0x12, 0xaf, 0xc0, 0x9a, 0x67, 0x40, 0x33, 0x63, 0x3b, 0xae, 0x9d, 0x52,
	0xa7, 0x41, 0x82, 0x55, 0xeb, 0xfb, 0x73, 0xce, 0xdc, 0x33, 0xe7, 0x4e, 0xa0, 0xc1, 0x31, 0xb5,
	0xc2, 0x28, 0xe0, 0x01, 0xd2, 0x42, 0xa7, 0xbd, 0x4e, 0x83, 0x80, 0x0e, 0x89, 0x8d, 0x43, 0xcf,
	0xc6, 0xbe, 0x1f, 0x70, 0xcc, 0xbd, 0xc0, 0x67, 0xaa, 0xa2, 0x7d, 0x27, 0xce, 0xca, 0x2f, 0x67,
	0x74, 0x6c, 0x9f, 0x45, 0x38, 0x0c, 0x49, 0x94, 0xe4, 0x1f, 0xca, 0x3f, 0x83, 0x1d, 0x4a, 0xfc,
	0x1d, 0x76, 0x86, 0x29, 0x25, 0x91, 0x1d, 0x84, 0x12, 0x61, 0x02, 0xda, 0x46, 0x1e, 0x8d, 0x7b,
	0x27, 0x84, 0x71, 0x7c, 0x12, 0xaa, 0x02, 0xf3, 0x9b, 0x06, 0xfa, 0x11, 0xa6, 0x68, 0x17, 0xea,
	0x1c, 0xd3, 0xbe, 0xe7, 0xb6, 0x2a, 0x9b, 0x95, 0x2d, 0xa3, 0xb3, 0x6e, 0xa9, 0x4e, 0x2b, 0xe9,
	0xb4, 0x5e, 0xf3, 0xc8, 0xf3, 0xe9, 0x1b, 0x3c, 0x1c, 0x91, 0x5e, 0x8d, 0x63, 0x7a, 0xe0, 0x22,
	0x0b, 0xf4, 0x77, 0xe4, 0xbc, 0xa5, 0x95, 0xe8, 0x10, 0x85, 0xa8, 0x03, 0xb5, 0x53, 0xf1, 0xd5,
	0xd2, 0xcb, 0x70, 0xc8, 0x52, 0xf4, 0x18, 0xe6, 0x06, 0x11, 0xc1, 0x3c, 0x88, 0x5a, 0xd5, 0x12,
	0x5d, 0x49, 0x31, 0x7a, 0x0a, 0x86, 0xfc, 0x97, 0xf4, 0xc5, 0xc8, 0xad, 0x9a, 0xec, 0x6d, 0x17,
	0x7a, 0x8f, 0x12, 0x3d, 0x7a, 0xa0, 0xca, 0x45, 0x40, 0x34, 0x8f, 0x42, 0x37, 0x6d, 0xae, 0x5f,
	0xdf, 0xac, 0xca, 0x45, 0xc0, 0xfc, 0xac, 0xc1, 0xe2, 0x9e, 0xc2, 0xc2, 0xb4, 0x47, 0xde, 0x8f,
	0x08, 0xe3, 0x89, 0x54, 0x95, 0xa9, 0xa5, 0xd2, 0x6e, 0x24, 0x95, 0x3e, 0x83, 0x54, 0xd5, 0x59,
	0xa4, 0xaa, 0x4d, 0x25, 0xd5, 0x73, 0x58, 0xca, 0x28, 0xc5, 0xc2, 0xc0, 0x67, 0xe4, 0x46, 0x56,
	0x34, 0xbf, 0x56, 0x60, 0x79, 0x9f, 0xb0, 0x41, 0xe4, 0x39, 0x02, 0x8c, 0x25, 0xba, 0xaf, 0x66,
	0xc0, 0xf4, 0xad, 0x46, 0xe2, 0xdc, 0xc5, 0xc4, 0xb9, 0x22, 0x26, 0x05, 0x5f, 0x19, 0x7b, 0x53,
	0xd6, 0x29, 0x49, 0xff, 0x9e, 0x34, 0x47, 0xb0, 0x72, 0x79, 0x9e, 0x58, 0x9d, 0x0d, 0x30, 0x78,
	0xc0, 0xf1, 0xb0, 0x3f, 0x08, 0x46, 0x3e, 0x97, 0x12, 0x35, 0x7b, 0x20, 0x43, 0x7b, 0x22, 0x82,
	0x6e, 0x43, 0x95, 0x63, 0xca, 0xe4, 0x6c, 0x46, 0x67, 0xce, 0x0a, 0x1d, 0x4b, 0xa8, 0x2b, 0x83,
	0xe6, 0x97, 0x0a, 0x2c, 0xbe, 0x0c, 0x5c, 0xef, 0xf8, 0x3c, 0xe3, 0xcd, 0x7f, 0x75, 0xf7, 0x85,
	0x3d, 0x32, 0x87, 0x9d, 0xc5, 0x1e, 0xdb, 0xb0, 0xb4, 0x4f, 0x86, 0x84, 0x97, 0xf0, 0x86, 0xf9,
	0x00, 0x50, 0xb6, 0x36, 0xa6, 0xbd, 0xa2, 0xf8, 0xa3, 0x06, 0x46, 0x8f, 0xb0, 0x60, 0x14, 0x0d,
	0x44, 0x3d, 0xda, 0x87, 0xff, 0xa3, 0xf8, 0xb3, 0x3f, 0xc5, 0x31, 0x9b, 0xd1, 0x18, 0xe3, 0xc0,
	0x45, 0xcf, 0xc0, 0x48, 0x51, 0x3c, 0xb7, 0x94, 0xc8, 0x90, 0x34, 0x1c, 0xb8, 0x19, 0x89, 0xf4,
	0xf2, 0x17, 0x3a, 0x8b, 0xd5, 0xcd, 0x43, 0x58, 0xea, 0x72, 0x8e, 0x07, 0x6f, 0x4b, 0xec, 0xde,
	0x46, 0x7e, 0x38, 0x91, 0xcb, 0x1c, 0xdf, 0x7c, 0x01, 0x28, 0x0b, 0xf6, 0xdb, 0x0b, 0xb8, 0x1e,
	0xed, 0x50, 0x5c, 0xfd, 0x9f, 0x3a, 0xda, 0x2b, 0xe1, 0x8d, 0xc2, 0xd1, 0xd6, 0x60, 0x4e, 0xa1,
	0xb1, 0x18, 0xae, 0x2e, 0xe1, 0x18, 0xba, 0x0b, 0xf3, 0x19, 0x3c, 0x16, 0x03, 0x1a, 0x63, 0x40,
	0xd6, 0xf9, 0x59, 0x05, 0x9d, 0x63, 0x8a, 0x1c, 0x68, 0xa4, 0x4f, 0x21, 0x5a, 0x11, 0x5b, 0x9b,
	0xff, 0x0d, 0x69, 0xaf, 0xe6, 0xa2, 0x8a, 0xdd, 0xdc, 0xba, 0xe8, 0xce, 0x23, 0x50, 0xf1, 0x4d,
	0x8e, 0xe9, 0x87, 0xef, 0x3f, 0x3e, 0x69, 0xcb, 0xe6, 0x82, 0x7d, 0xfa, 0xc8, 0xe6, 0x98, 0xda,
	0xea, 0x9a, 0x9e, 0x54, 0xb6, 0x11, 0x85, 0xf9, 0xec, 0x9b, 0x82, 0xd6, 0x04, 0xe0, 0x84, 0x57,
	0xb3, 0xdd, 0x2a, 0x26, 0x62, 0xb2, 0x7b, 0x17, 0xdd, 0x05, 0x94, 0xa2, 0xa4, 0x74, 0x4d, 0xf3,
	0xbf, 0x98, 0x8e, 0x09, 0x22, 0x07, 0x1a, 0xe9, 0xe2, 0xaa, 0x61, 0xf2, 0x8f, 0x8e, 0x1a, 0xa6,
	0xb0, 0xdd, 0xf1, 0x30, 0x2a, 0x3e, 0x69, 0x98, 0x13, 0x99, 0x11, 0x1c, 0xc7, 0x00, 0xe3, 0x35,
	0x45, 0xab, 0xea, 0xc4, 0xb9, 0x15, 0x6f, 0xdf, 0xca, 0x87, 0x63, 0x9a, 0xfb, 0x17, 0xdd, 0x26,
	0x32, 0x54, 0x42, 0xd0, 0xb0, 0x3c, 0x8f, 0x2b, 0x53, 0x31, 0xcf, 0xd8, 0x8d, 0x8a, 0xa7, 0x60,
	0x75, 0xc5, 0x53, 0x34, 0x6d, 0xcc, 0xa3, 0x12, 0x13, 0x79, 0xb0, 0x4c, 0xa5, 0xf3, 0x5c, 0xe6,
	0x29, 0xf8, 0x36, 0x99, 0xe7, 0x0a, 0x1e, 0x95, 0xb8, 0x62, 0x9e, 0x98, 0xc7, 0xa9, 0xcb, 0x55,
	0xde, 0xfd, 0x15, 0x00, 0x00, 0xff, 0xff, 0x27, 0xe3, 0x38, 0x47, 0x96, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TagClient is the client API for Tag service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TagClient interface {
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	DescribeTags(ctx context.Context, in *DescribeTagsRequest, opts ...grpc.CallOption) (*DescribeTagsResponse, error)
	ModifyTag(ctx context.Context, in *ModifyTagRequest, opts ...grpc.CallOption) (*ModifyTagResponse, error)
	DeleteTags(ctx context.Context, in *DeleteTagsRequest, opts ...grpc.CallOption) (*DeleteTagsResponse, error)
	AttachTags(ctx context.Context, in *AttachTagsRequest, opts ...grpc.CallOption) (*AttachTagsResponse, error)
	DetachTags(ctx context.Context, in *DetachTagsRequest, opts ...grpc.CallOption) (*DetachTagsResponse, error)
}

type tagClient struct {
	cc *grpc.ClientConn
}

func NewTagClient(cc *grpc.ClientConn) TagClient {
	return &tagClient{cc}
}

func (c *tagClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, "/pb.tag/CreateTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) DescribeTags(ctx context.Context, in *DescribeTagsRequest, opts ...grpc.CallOption) (*DescribeTagsResponse, error) {
	out := new(DescribeTagsResponse)
	err := c.cc.Invoke(ctx, "/pb.tag/DescribeTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) ModifyTag(ctx context.Context, in *ModifyTagRequest, opts ...grpc.CallOption) (*ModifyTagResponse, error) {
	out := new(ModifyTagResponse)
	err := c.cc.Invoke(ctx, "/pb.tag/ModifyTag", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) DeleteTags(ctx context.Context, in *DeleteTagsRequest, opts ...grpc.CallOption) (*DeleteTagsResponse, error) {
	out := new(DeleteTagsResponse)
	err := c.cc.Invoke(ctx, "/pb.tag/DeleteTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) AttachTags(ctx context.Context, in *AttachTagsRequest, opts ...grpc.CallOption) (*AttachTagsResponse, error) {
	out := new(AttachTagsResponse)
	err := c.cc.Invoke(ctx, "/pb.tag/AttachTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagClient) DetachTags(ctx context.Context, in *DetachTagsRequest, opts ...grpc.CallOption) (*DetachTagsResponse, error) {
	out := new(DetachTagsResponse)
	err := c.cc.Invoke(ctx, "/pb.tag/DetachTags", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagServer is the server API for Tag service.
type TagServer interface {
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	DescribeTags(context.Context, *DescribeTagsRequest) (*DescribeTagsResponse, error)
	ModifyTag(context.Context, *ModifyTagRequest) (*ModifyTagResponse, error)
	DeleteTags(context.Context, *DeleteTagsRequest) (*DeleteTagsResponse, error)
	AttachTags(context.Context, *AttachTagsRequest) (*AttachTagsResponse, error)
	DetachTags(context.Context, *DetachTagsRequest) (*DetachTagsResponse, error)
}

func RegisterTagServer(s *grpc.Server, srv TagServer) {
	s.RegisterService(&_Tag_serviceDesc, srv)
}

func _Tag_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.tag/CreateTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_DescribeTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).DescribeTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.tag/DescribeTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).DescribeTags(ctx, req.(*DescribeTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_ModifyTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).ModifyTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.tag/ModifyTag",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).ModifyTag(ctx, req.(*ModifyTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_DeleteTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).DeleteTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.tag/DeleteTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).DeleteTags(ctx, req.(*DeleteTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_AttachTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).AttachTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.tag/AttachTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).AttachTags(ctx, req.(*AttachTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tag_DetachTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagServer).DetachTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.tag/DetachTags",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagServer).DetachTags(ctx, req.(*DetachTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Tag_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.tag",
	HandlerType: (*TagServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTag",
			Handler:    _Tag_CreateTag_Handler,
		},
		{
			MethodName: "DescribeTags",
			Handler:    _Tag_DescribeTags_Handler,
		},
		{
			MethodName: "ModifyTag",
			Handler:    _Tag_ModifyTag_Handler,
		},
		{
			MethodName: "DeleteTags",
			Handler:    _Tag_DeleteTags_Handler,
		},
		{
			MethodName: "AttachTags",
			Handler:    _Tag_AttachTags_Handler,
		},
		{
			MethodName: "DetachTags",
			Handler:    _Tag_DetachTags_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tag.proto",
}
